### ISSUE TITLE
[Roadmap] Feature-Implementation-Tasks for the near future

### ISSUE THREAD

**Issue by orgua** [nes-lab/shepherd#34]
## Modus Operandi

- users can report
  - missing features that improve usage
  - bugs
  - overly complicated workflow-details
  - etc.
- list is ordered roughly by importance (order of execution)

## Done

- [x] fix programming of unaligned hex, #33
- [x] log systemd services
- [x] determine cause of bad rf-performance for targets
- [x] simplify extraction of gpio-traces (datalib) -> is csv ok? `shepherd-data extract-gpio`
- [x] lint all subprojects (ruff, pyright)
- [x] verification of vsrc (`c` in PRU vs `py`-port)
- [x] sheep - error handling + saving message log & files -> report-model?
- [x] add feedback-path from source to harvester (improves boost-less converters on ivcurve)
- [x] add extrapolation for constant-voltage-harvester (for ivcurve)
- [x] deploy improved version of targets v1.3 (better RF & more GPIO)
   - [x] send to manufacturing
   - [x] test-assemble
   - [x] send to assembly
- [x] testbed-maintenance
   - [x] add rpi ptp-server
   - [x] add new ssl-certificates
   - [x] measure sync 

All open Tasks got migrated to #82
