### ISSUE TITLE
[Roadmap] Milestone - Bringing the Testbed online

### ISSUE THREAD

**Issue by orgua** [nes-lab/shepherd#39]
Roadmap for May-August 2023

- targets
   - [x] SW, prepare set of firmwares
   - [x] SW, firmware patching (verification, conversion, modification)
   - [x] SW, programmer (swd tested, sbw tbd)
   - [x] SW, firmwares for selftesting
   - [x] HW, assembly
   - [x] HW, test (10/18 fully working)
- capes
   - [x] HW, THT assembly (0/10) (**in progress**)
   - [x] SW, test & calibration
- BBone
   - [x] HW, POE Converter assembly & test
   - [x] SW, Update OS (ubuntu 22.04, py3.10)
   - [x] SW, sheep & herd -> task, core-integration
   - [x] HW, deployment (update, test) (**in progress**)
- misc
   - [x] SW, datalayout (config, metadata, meas) -> core-lib
   - [x] SW, time sync investigation
   - [x] SW, include Trafficbench to get linkmatrix
      - [x] find schedule and prepare FW
      - [x] prepare [python-code](https://github.com/orgua/shepherd-targets/commit/e5f551d72eabad6dfdc93d77cdbf2eddec604fa5) for inclusion
      - [x] include software into shepherd
      - [x] digital waveform to uart converter (& disable flow control)
      - [x] test & bugfixes
    - [x] switch to pydantic v2
    - [x] update general documentation
    - [x] describe testbed (usage, structure)
    - [x] generate &| integrate energy-envs
    - [x] integrate default-firmwares
    - [x] get allowances for deployment in offices 
    - [x] case - laser-cut (**in production**)
- testbed-frontend
   - [x] add DNS to server: shepherd.cfaed.tu-dresden.de
   - [x] testbedClient & Mockup (fixture-loader)
